project:
  type: book
  output-dir: docs

book:
  title: "Basic statitics concepts cours in R"
  subtitle: "Foundations of statistical reasoning, data interpretation, and evidence-based decision making"
  author:
    - name: "Sufyan Suleman"
      affiliation: "Novo Nordisk Foundation Center for Basic Metabolic Research, University of Copenhagen Denmark"
    - name: "Asmat Ullah"
      affiliation: "Department of Biomedicine, Faculty of Health, Aarhus University Denmark"
  chapters:
  - index.qmd
  - part: "Programme"
    chapters:
    - programme/schedule.qmd
  - part: "Sessions"
    chapters:
    - sessions/01-descriptive-statistics.qmd
    - sessions/02-linear-regression.qmd
    - sessions/03-logistic-regression.qmd
    - sessions/04-t-tests.qmd
    - sessions/05-anova.qmd
    - sessions/06-multiple-regression.qmd
    - sessions/basic-statistics.qmd
    - sessions/tidy-data-wrangling.qmd
    - sessions/reproducible-research.qmd
    - sessions/advanced-visualization.qmd
    - sessions/clinical-research-methods.qmd
    - sessions/survival-and-time-to-event.qmd
    - sessions/explore-clinical-data.qmd
    - sessions/help-docs.qmd

  appendices:
    - LICENSE.md
    - appendix/references.qmd
    - appendix/discussion.qmd
    - appendix/acknowledgements.qmd
  page-footer:
    center:
      - text: "License: CC BY 4.0"
        href: LICENSE.html

bibliography:
  - includes/references.bib
csl: includes/vancouver.csl

editor:
  markdown:
    wrap: 72
    canonical: true

format:
  html:
    include-after-body:
      - "includes/site-counter.html"
    theme: "cosmo"


execute:
  freeze: auto
