---
search: false
# Relative to main project
bibliography: ../includes/references.bib
csl: ../includes/vancouver.csl
---

# Why use R? {.center}

-   It is free and open-source
-   Ability to handle large datasets efficiently
-   Versatility in statistical analysis
-   Superior Data Visualization
-   Community and support

::: notes
-   **Open Source and Free**: Unlike STATA, R is completely free,
    lowering barriers to entry for students and researchers.

-   **Ability to Handle Large Datasets**: R's ability to handle large or
    complex datasets is superior to Excel and comparable to STATA.

-   **Advanced Statistical Analysis**: R provides sophisticated tools
    for deep statistical analysis, outperforming basic functionalities
    in Excel and STATA.

-   **Versatility Across Disciplines**: R's wide range of packages makes
    it adaptable for use in diverse fields, from genomics to
    quantitative finance.

-   **Superior Data Visualization**: R's ggplot2 and other visualization
    libraries offer more advanced graphical capabilities than Excel.

-   **Community and Support**: R boasts a large, active community,
    offering extensive resources, help, and shared code.

-   **Reproducibility**: R scripts ensure reproducibility of analyses, a
    critical component in research that Excel and STATA handle less
    efficiently.

-   **Continuous Innovation**: Being open-source, R continuously
    integrates the latest statistical methods and tools faster than
    commercial software.
:::

# How do you analyze data {.center}

-   Do you work with data?
-   How do you analyze data?

::: notes
-   Motivation for This Course

we aim to equip you with the skills necessary to transform raw data into
insightful, actionable information. Whether you're just starting your
journey in data analysis or looking to enhance your skill set, this
course offers something valuable for you.

-   **Empowerment Through Knowledge:** By learning R, you gain access to
    a powerful suite of statistical and graphical techniques. This
    knowledge empowers you to make informed decisions, uncover trends,
    and tell stories through data.

-   **Versatility Across Industries:** R is used globally across various
    sectors, including healthcare, finance, academia, and technology.
    Mastering R opens doors to opportunities in these and many other
    industries.

-   **Community and Support:** The R community is vast and supportive,
    offering a wealth of resources, libraries, and forums. As part of
    this course, you'll learn how to tap into this community to find
    solutions, collaborate on projects, and continue growing as a data
    analyst.

-   **Hands-On Learning Experience:** This course is designed with
    beginners in mind, focusing on practical, real-world applications
    of R. Through interactive exercises, projects, and examples, you'll
    build a strong foundation in data analysis that will serve you well
    throughout your career.

Join us on this journey to discover the power of R programming.
Together, we'll unlock the potential of data analysis, giving you the
tools and confidence to tackle any data challenge that comes your way.
:::

# Why are you here? {.center}
