# Discussion

As you get started with R, the role of your network becomes increasingly
important both for continued learning, but also for collaboration with
others skilled in R. This course is a great opportunity to meet others.

You can also use the discussion forum to ask questions, share a cool
resource, or just say hi to each other!

## Day 1 {#discussion-day-1 .unnumbered}

After lunch we will do a rapid activity. I will divide you in discussion
groups of 3-4 people. In your group, take turns to answer the following
questions:

-   Why are you here and what are your expectations from learning R?
-   Have you done any courses before this one? If yes, what did you like
    about them and what did you not like?
-   How did you hear about this course?

## Day 2 {#discussion-day-2 .unnumbered}

After lunch, get in your groups and discuss these topics:

-   Share your experience of data analysis. E.g. what kind of data do
    you work with, what kind of analysis do you do, what kind of
    software do you use, etc.
-   Share limitations you have experienced with your current software
    and/or workflow. Do you like to keep doing it the same way or
    improve it? and Why?
-   What do you think about R? Do you think it can help you with your
    work? Why?
-   What do you think about RStudio? Do you think it can help you with
    your work? Why?
