# References

1.  **R Core Team**. (2023). *R: A language and environment for
    statistical computing*. R Foundation for Statistical Computing.
    <https://www.R-project.org/>.

2.  **Wickham, H., & Grolemund, G.** (2017). *R for Data Science:
    Import, Tidy, Transform, Visualize, and Model Data*. O'Reilly Media,
    Inc. <https://r4ds.had.co.nz/>.

3.  **Chang, W.** (2018). *R Graphics Cookbook: Practical Recipes for
    Visualizing Data*. O'Reilly Media. <https://r-graphics.org/>.

4.  **RStudio Team**. (2023). *RStudio: Integrated Development
    Environment for R*. RStudio, PBC. <http://www.rstudio.com/>.

5.  **Wickham, H.** (2016). *ggplot2: Elegant Graphics for Data
    Analysis*. Springer-Verlag New York. <https://ggplot2-book.org/>.

6.  **Wickham, H.** (2017). *readr: Read Rectangular Text Data*. R
    package version 1.3.1. <https://CRAN.R-project.org/package=readr>.

7.  **Fisher, R. A.** (1936). *The use of multiple measurements in
    taxonomic problems*. Annals of Eugenics, 7(2), 179-188. (Original
    description of the iris dataset).

8.  **Henderson, H. V., & Velleman, P. F.** (1981). *Building multiple
    regression models interactively*. Biometrics, 37, 391-411.
    (Description of the mtcars dataset).

9.  **Matloff, N.** (2011). *The Art of R Programming: A Tour of
    Statistical Software Design*. No Starch Press.
    <https://nostarch.com/artofr.htm>.

10. **Teetor, P.** (2011). *R Cookbook: Proven Recipes for Data
    Analysis, Statistics, and Graphics*. O'Reilly Media.

11. **Stack Overflow - R Tag**. Community-based Q&A for R programming.
    <https://stackoverflow.com/questions/tagged/r>.

12. **CRAN (Comprehensive R Archive Network)**. Source for R packages
    and documentation. <https://cran.r-project.org/>.
